"""course source roadmap_slug

Revision ID: 7c0ca6d47b38
Revises: 4c2c0a3fbab4
Create Date: 2026-09-26 15:39:36.935756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c0ca6d47b38'
down_revision: Union[str, Sequence[str], None] = '4c2c0a3fbab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('source', sa.String(), server_default='ai', nullable=False))
    op.add_column('courses', sa.Column('roadmap_slug', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'roadmap_slug')
    op.drop_column('courses', 'source')
    # ### end Alembic commands ###
