"""qa thread chat

Revision ID: be00e974832b
Revises: 7c0ca6d47b38
Create Date: 2026-09-26 16:05:23.194987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be00e974832b'
down_revision: Union[str, Sequence[str], None] = '7c0ca6d47b38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_questions', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('lab_questions', sa.Column('role', sa.String(), nullable=True))
    op.add_column('lab_questions', sa.Column('conversation_id', sa.String(), nullable=True))
    op.alter_column('lab_questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'lab_questions', 'lab_questions', ['parent_id'], ['id'])
    op.add_column('lesson_questions', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('lesson_questions', sa.Column('role', sa.String(), nullable=True))
    op.add_column('lesson_questions', sa.Column('conversation_id', sa.String(), nullable=True))
    op.alter_column('lesson_questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_foreign_key(None, 'lesson_questions', 'lesson_questions', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lesson_questions', type_='foreignkey')
    op.alter_column('lesson_questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('lesson_questions', 'conversation_id')
    op.drop_column('lesson_questions', 'role')
    op.drop_column('lesson_questions', 'parent_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lab_questions', type_='foreignkey')
    op.alter_column('lab_questions', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('lab_questions', 'conversation_id')
    op.drop_column('lab_questions', 'role')
    op.drop_column('lab_questions', 'parent_id')
    # ### end Alembic commands ###
